FROM rust:slim

# USER root

# RUN apt-get update --fix-missing && \
#     apt-get install -y curl git --fix-missing && \
#     useradd -ms /bin/bash foundry

# RUN curl -L https://foundry.paradigm.xyz | bash && \
#     source /root/.bashrc && \
#     foundryup
